('stream ended at an unexpected time', 11) http://about.com/
KeyboardInterrupt
Fri Jul 14 13:54:33 2017
Traceback (most recent call last):
  File "./main.py", line 423, in <module>
    main()
  File "./main.py", line 414, in main
    http_pinger.run()
  File "./main.py", line 276, in run
    self.pool.join()
  File "/home/thunder/Envs/AMTP/lib/python3.6/site-packages/gevent/pool.py", line 552, in join
    result = self._empty_event.wait(timeout=timeout)
  File "/home/thunder/Envs/AMTP/lib/python3.6/site-packages/gevent/event.py", line 219, in wait
    return self._wait(timeout)
  File "/home/thunder/Envs/AMTP/lib/python3.6/site-packages/gevent/event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "/home/thunder/Envs/AMTP/lib/python3.6/site-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/home/thunder/Envs/AMTP/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
KeyboardInterrupt
